import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import DashboardWidget from "./dashboard/components/DashboardWidget";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} h-full`}>
          <header className="flex justify-between items-center p-4 bg-white shadow">
            <h1 className="text-lg font-semibold text-gray-700">
              Admin Dashboard
            </h1>
            <div>
              <SignedOut>
                <SignInButton>
                  <button className="px-4 py-2 bg-blue-500 text-white rounded-md shadow-md hover:bg-blue-600">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="ml-2 px-4 py-2 bg-gray-300 text-black rounded-md shadow-md hover:bg-gray-400">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
